<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Requests\StoreRecurringIncomeRequest;
use App\Http\Requests\UpdateRecurringIncomeRequest;
use App\Models\RecurringIncome;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;

class RecurringIncomeController extends Controller
{
    public function index(Request $request): JsonResponse
    {
        $query = $request->user()
            ->recurringIncomes()
            ->with('wallet')
            ->withCount('incomes');

        if ($request->has('active')) {
            $query->where('active', $request->boolean('active'));
        }

        $incomes = $query->orderBy('name')->get();

        return response()->json([
            'data' => $incomes,
        ]);
    }

    public function store(StoreRecurringIncomeRequest $request): JsonResponse
    {
        $income = $request->user()->recurringIncomes()->create(
            $request->validated()
        );

        $income->load('wallet');

        return response()->json([
            'message' => 'Receita recorrente criada com sucesso.',
            'data' => $income,
        ], 201);
    }

    public function show(Request $request, int $id): JsonResponse
    {
        $income = $request->user()
            ->recurringIncomes()
            ->with('wallet')
            ->withCount([
                'incomes',
                'incomes as received_count' => function ($query) {
                    $query->where('status', 'received');
                },
                'incomes as pending_count' => function ($query) {
                    $query->where('status', 'pending');
                },
            ])
            ->findOrFail($id);

        return response()->json([
            'data' => $income,
        ]);
    }

    public function update(UpdateRecurringIncomeRequest $request, int $id): JsonResponse
    {
        $income = $request->user()
            ->recurringIncomes()
            ->findOrFail($id);

        $income->update($request->validated());

        return response()->json([
            'message' => 'Receita recorrente atualizada com sucesso.',
            'data' => $income->fresh()->load('wallet'),
        ]);
    }

    public function destroy(Request $request, int $id): JsonResponse
    {
        $income = $request->user()
            ->recurringIncomes()
            ->findOrFail($id);

        // Soft-delete pending incomes generated by this recurring template
        $income->incomes()->where('status', 'pending')->delete();

        $income->delete();

        return response()->json([
            'message' => 'Receita recorrente removida com sucesso.',
        ]);
    }

    public function activate(Request $request, int $id): JsonResponse
    {
        $income = $request->user()
            ->recurringIncomes()
            ->findOrFail($id);

        $income->activate();

        return response()->json([
            'message' => 'Receita recorrente ativada com sucesso.',
            'data' => $income->fresh(),
        ]);
    }

    public function deactivate(Request $request, int $id): JsonResponse
    {
        $income = $request->user()
            ->recurringIncomes()
            ->findOrFail($id);

        $income->deactivate();

        return response()->json([
            'message' => 'Receita recorrente desativada com sucesso.',
            'data' => $income->fresh(),
        ]);
    }
}
